<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginOrange</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>63a17c5f-9f3e-4cd6-bce4-680e1a06decf</testSuiteGuid>
   <testCaseLink>
      <guid>6cb8afe1-ffb5-4327-a8cc-61620499ec4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM/Login/common_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>506f9a8c-7e39-4c9e-8ceb-8b585d32d8e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78e67382-30bb-4167-9990-a7d5f11b6fbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e586f73f-a7f8-4ddf-a71e-7aa12f2881c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM/Login/Successfully Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18a3b127-39b0-41e7-aaa6-277b782cec7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827e6eed-45ec-49e5-a567-31011e1f048f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0bbe40f6-f5a5-4951-8219-3decb0d26067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM/Login/User enter incorrect username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4280813f-6cb0-42f2-af82-127060591604</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b2444e3-e5ec-47e6-bebe-6450f654e115</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f03f3d6-1d8f-4780-9133-31b7bc568eb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>077a493e-1e74-4607-9f65-3f01fe5dcfb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM/Login/Users enter incorrect password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f23fd5b8-44f6-49ba-9266-2d1fe25d38c6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Invalid_Username_DD</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e327bd7c-cfb4-416e-aa57-835748e36a1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>962b1c15-3243-4082-8a87-c36c72ca6205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37805607-bbe9-4cd1-84bf-258c82ca00aa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
